### ISSUE TITLE
Slides Template

### ISSUE THREAD

**Issue by h3ssto** [SoftVarE-Group/BibTags#22]
### Todo
* [ ] No space before and after multicols
* [ ] Less padding left and right
* [ ] More space around lists, less space between entries, use of vfill  
* [ ] Automatically insert subsection title on each slide, avoid line break in title
    * Specify "automatic", title is now fixed and as wide as page, subtitle was present but commented out.
* [ ] ~~Arrange content vertically centered~~ and use more space on top
* [x] Heading moves upwards when more content is added 
* [ ] Overview pages when sections/chapters start
* [ ] Avoid path to titlepage
    * Unclear 
* [ ] Nice table of contents
* [ ] Footer missing when using pause inside
   * That is the intended behaviour of `\pause`, use `\uncover`, `\only`, and the `<...>`-Syntax 
* [ ] Enumerate does not have numbers
   * Position marked with `%TODO`
